#include "FogController.h"
#include "Components/SphereComponent.h"
#include "NiagaraComponent.h"
#include "NiagaraFunctionLibrary.h"

AFogController::AFogController()
{
    PrimaryActorTick.bCanEverTick = true;

    // ğŸ”¹ ì¶©ëŒ ê°ì§€ìš© Sphere ì„¤ì •
    FogCollision = CreateDefaultSubobject<USphereComponent>(TEXT("FogCollision"));
    FogCollision->SetupAttachment(RootComponent);
    FogCollision->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
    FogCollision->SetCollisionResponseToAllChannels(ECR_Overlap);
    FogCollision->SetSphereRadius(InitialRadius);

    // ğŸ”¹ ë‚˜ì´ì•„ê°€ë¼ Fog íš¨ê³¼ (Niagara ì‹œìŠ¤í…œì€ ì—ë””í„°ì—ì„œ ì§ì ‘ ì„¤ì •í•´ì•¼ í•¨)
    FogEffect = CreateDefaultSubobject<UNiagaraComponent>(TEXT("FogEffect"));
    FogEffect->SetupAttachment(RootComponent);
}

void AFogController::BeginPlay()
{
    Super::BeginPlay();
    CurrentRadius = InitialRadius;

    // ğŸ”¹ ë‚˜ì´ì•„ê°€ë¼ ì‹œìŠ¤í…œ í™œì„±í™”
    if (FogEffect)
    {
        FogEffect->Activate();
        FogEffect->SetWorldScale3D(FVector(InitialRadius / 100.0f));
    }
}

void AFogController::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    if (CurrentRadius > MinRadius)
    {
        CurrentRadius -= ShrinkRate * DeltaTime;

        // ğŸ”¹ ì¶©ëŒ ê°ì§€ìš© Sphere í¬ê¸° ì—…ë°ì´íŠ¸
        FogCollision->SetSphereRadius(CurrentRadius);

        // ğŸ”¹ Niagara Fog í¬ê¸° ì—…ë°ì´íŠ¸ (ì ì  ì¤„ì–´ë“œëŠ” íš¨ê³¼)
        if (FogEffect)
        {
            FogEffect->SetNiagaraVariableFloat(TEXT("User.FogRadius"), CurrentRadius);
            FogEffect->SetWorldScale3D(FVector(CurrentRadius / 100.0f));

            // ğŸ”¹ Fogë¥¼ ì¤‘ì•™ìœ¼ë¡œ ì´ë™
            FVector FogLocation = FogEffect->GetComponentLocation();
            FogLocation = FMath::VInterpTo(FogLocation, FVector(0, 0, FogLocation.Z), DeltaTime, 0.3f);
            FogEffect->SetWorldLocation(FogLocation);
        }
    }
}
