// Fill out your copyright notice in the Description page of Project Settings.


#include "MyAIController.h"
#include "Kismet/GameplayStatics.h"

#include "BehaviorTree/BlackboardComponent.h"
#include "BehaviorTree/BehaviorTreeComponent.h"
#include "BehaviorTree/BehaviorTree.h"
#include "BehaviorTree/BlackboardData.h"

#include "Navigation/PathFollowingComponent.h"
#include "../Character/BaseCharacter.h"
#include "TimerManager.h"

#include "Perception/AIPerceptionComponent.h"
#include "Perception/AISense.h"
#include "Perception/AISense_Sight.h"  // ì‹œê° ì„¼ì„œ ì¶”ê°€
#include "Perception/AISense_Hearing.h"
#include "Perception/AISense_Damage.h"
#include "Perception/AIPerceptionSystem.h"

AMyAIController::AMyAIController(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
{
    PrimaryActorTick.bCanEverTick = true; // Tick í™œì„±í™”

    // BehaviorTree ì• ì…‹ ë¡œë“œ
    static ConstructorHelpers::FObjectFinder<UBehaviorTree> BTAsset(TEXT("/Game/WorkFolder/AI/AIPlayer/BT_AIPlayer.BT_AIPlayer"));
    if (BTAsset.Succeeded()) 
    {
        AIBehavior = BTAsset.Object; 
    }

    // Blackboard ì• ì…‹ ë¡œë“œ
    static ConstructorHelpers::FObjectFinder<UBlackboardData> BBAsset(TEXT("/Game/WorkFolder/AI/AIPlayer/BB_AIPlayer.BB_AIPlayer"));
    if (BBAsset.Succeeded()) 
    {
        BlackboardData = BBAsset.Object;
    }

    // Perception Component ìƒì„± ë° ì´ˆê¸°í™”
    AIPerceptionComponent = CreateDefaultSubobject<UAIPerceptionComponent>(TEXT("AIPerceptionComponent"));
}

void AMyAIController::BeginPlay()
{
    Super::BeginPlay();

    // ì‹œì‘í•˜ìë§ˆì Behavior Tree í™œì„±í™” -> ë ˆë²¨ì— ë°°ì¹˜í•˜ìë§ˆì ì‹¤í–‰ë¨
    if (AIBehavior && BlackboardData)
    {
        UBlackboardComponent* BlackboardPtr = Blackboard.Get();

        if (UseBlackboard(BlackboardData, BlackboardPtr))
        {
            // ì‹¤ì œ Blackboard Assetì— IsRunningì´ë¼ëŠ” í‚¤ê°€ ìˆì–´ì•¼ í•œë‹¤.
            IsRunningKey.SelectedKeyName = FName(TEXT("IsRunning"));
            BlackboardPtr->SetValueAsBool(IsRunningKey.SelectedKeyName, true);

            // "AIState" ì„¤ì •
            // AIStateKey.SelectedKeyName = FName(TEXT("AIState"));
            // BlackboardPtr->SetValueAsEnum(AIStateKey.SelectedKeyName, static_cast<uint8>(EAIState::Patrol));

            DefendRadiusKey.SelectedKeyName = FName(TEXT("DefendRadius"));
            BlackboardPtr->SetValueAsFloat(DefendRadiusKey.SelectedKeyName, 600.f); // 350

            AttackRadiusKey.SelectedKeyName = FName(TEXT("AttackRadius"));
            BlackboardPtr->SetValueAsFloat(AttackRadiusKey.SelectedKeyName, 600.f);
        }

        if (AIPerceptionComponent) 
        {
            TargetKey.SelectedKeyName = FName(TEXT("Target"));
            BlackboardPtr->SetValueAsObject(TargetKey.SelectedKeyName, nullptr);

            AIPerceptionComponent->OnPerceptionUpdated.AddDynamic(this, &AMyAIController::OnPerceptionUpdated);
        }
    }
#if 1
    StartBehaviorTree(); 
#endif

    // BB ì—ë””í„°ì— í‚¤ê°€ ì¶”ê°€ë˜ì–´ì•¼ í•œë‹¤.
    /*APawn* PlayerPawn = UGameplayStatics::GetPlayerPawn(GetWorld(), 0);
    GetBlackboardComponent()->SetValueAsVector(TEXT("PlayerLocation"), PlayerPawn->GetActorLocation() );
    GetBlackboardComponent()->SetValueAsVector(TEXT("StartLocation"), GetPawn()->GetActorLocation());*/

    // -> ê²½ë¡œ ì¶œë ¥
    //FAIMoveRequest MoveRequest;
    //MoveRequest.SetGoalLocation(FVector(0, 0, 0));
    //MoveRequest.SetAcceptanceRadius(15.f);
    //FNavPathSharedPtr NavPath;
    //MoveTo(MoveRequest, OUT& NavPath);
    //if (NavPath.IsValid())
    //{
    //    TArray<FNavPathPoint>& PathPoints = NavPath->GetPathPoints();
    //    for (const auto& Point : PathPoints)
    //    {
    //        const FVector& Location = Point.Location;
    //        DrawDebugSphere(GetWorld(), Location, 12.f, 12, FColor::Red, false, 10.0f);
    //    }
    //}
}

void AMyAIController::StartBehaviorTree()
{
    if (AIBehavior != nullptr)
    {
        SetControlMode(AIControlMode::BehaviorTree);
        RunBehaviorTree(AIBehavior);
    }
}

void AMyAIController::SetControlMode(AIControlMode mode)
{
    switch (mode)
    {
    case AIControlMode::BehaviorTree:
        UE_LOG(LogTemp, Log, TEXT("Control Mode: BehaviorTree"));
        ControlMode = AIControlMode::BehaviorTree;
        break;

    case AIControlMode::AIController:
        UE_LOG(LogTemp, Log, TEXT("Control Mode: AIController"));
        ControlMode = AIControlMode::AIController;
        break;
    }
}

void AMyAIController::ResumeBehaviorTree()
{
    if (UBehaviorTreeComponent* BTComp = Cast<UBehaviorTreeComponent>(BrainComponent))
    {
        // Behavior TreeëŠ” ë£¨íŠ¸ ë…¸ë“œë¶€í„° ë‹¤ì‹œ ì‹œì‘í•©ë‹ˆë‹¤. ì´ë•Œ Blackboard ê°’ì€ ê·¸ëŒ€ë¡œ ìœ ì§€
        SetControlMode(AIControlMode::BehaviorTree);
        BTComp->RestartTree(EBTRestartMode::ForceReevaluateRootNode);
    }
}

void AMyAIController::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    ABaseCharacter* AI = Cast<ABaseCharacter>(GetPawn());
    if (AI == nullptr) return;
    
    UBlackboardComponent* BlackboardComponent = GetBlackboardComponent();
    if (!BlackboardComponent) return;

    if (AI->GetIsDead())
    {
        // AIê°€ ì£½ì—ˆìœ¼ë©´ Behavior Treeë¥¼ ë©ˆì¶¤
        if (UBehaviorTreeComponent* BehaviorTreeComponent = Cast<UBehaviorTreeComponent>(BrainComponent))
        {
            SetControlMode(AIControlMode::AIController);
            ClearFocus(EAIFocusPriority::Gameplay);  // Focus í•´ì œ
            BehaviorTreeComponent->StopTree(); 
        }
    }

    // íƒ€ê²Ÿì´ ì£½ì—ˆëŠ”ì§€ í™•ì¸
    CheckAndDisableTargetIfDead();

    // Blackboardì—ì„œ í‚¤ì˜ FKeyë¥¼ ê°€ì ¸ì˜´
    FBlackboard::FKey IsRunningKeyID = BlackboardComponent->GetKeyID(IsRunningKey.SelectedKeyName); 

    bool bIsRunning = false;
    if (IsRunningKeyID != FBlackboard::InvalidKey) {
        bIsRunning = BlackboardComponent->GetValueAsBool(IsRunningKey.SelectedKeyName);
    }

    // ëª©í‘œ ì†ë„ ì„¤ì • (ë‹¬ë¦¬ê¸° ìƒíƒœì— ë”°ë¼ ë‹¬ë¼ì§)
    float TargetSpeed = bIsRunning ? AI->default_run_speed : AI->default_walk_speed;

    // í˜„ì¬ ì†ë„ë¥¼ ëª©í‘œ ì†ë„ë¡œ ì ì§„ì ìœ¼ë¡œ ë³€ê²½
    AI->current_speed = FMath::FInterpTo(AI->current_speed, TargetSpeed, DeltaTime, AI->speed_change_rate);

    // ìºë¦­í„°ì˜ ì´ë™ ì†ë„ ì—…ë°ì´íŠ¸
    AI->SetWalkSpeed(AI->current_speed);

    
    if (ControlMode != AIControlMode::AIController) return;

#if 0
    // [ ë³´ì´ëŠ”ì§€ í™•ì¸í•´ì„œ ì«“ì•„ê°€ì„œ ì˜ê±°ë‚˜ ë§ˆì§€ë§‰ìœ¼ë¡œ ë°œê²¬í•œ ìœ„ì¹˜ì— ê°€ê¸° ] : BT 
    // í”Œë ˆì´ì–´ ì‹œì•¼ì— ë“¤ì–´ì˜¤ë©´ ì³ë‹¤ë³´ê¸° 
    APawn* PlayerPawn = UGameplayStatics::GetPlayerPawn(GetWorld(), 0);
    //
    if (LineOfSightTo(PlayerPawn))
    {
        // Actor ì³ë‹¤ë³´ê³  ë”°ë¼ì˜¤ëŠ”ê±°
    //    MoveToActor(PlayerPawn, AcceptanceRadius);
    //    SetFocus(PlayerPawn);
        SetFocalPoint(PlayerPawn->GetActorLocation() + FVector(0, 0, 50)); // í”Œë ˆì´ì–´ ì¤‘ì•™(50cm ìœ„)ë¥¼ ë°”ë¼ë³´ê²Œ í•˜ê¸°

        // ì‹œì•¼ì— ë³´ì´ë©´ Plaeyr ë”°ë¼ê°€ê³  ì•„ë‹ˆë©´ ì§€ìš°ê¸° 
        GetBlackboardComponent()->SetValueAsVector(TEXT("PlayerLocation"), PlayerPawn->GetActorLocation());
        GetBlackboardComponent()->SetValueAsVector(TEXT("LastKnownPlayerLocation"), PlayerPawn->GetActorLocation());
        // ë°œì‚¬ ë°©í–¥ ë””ë²„ê¹…
    //    DrawDebugLine(GetWorld(), GetOwner()->GetActorLocation(), PlayerPawn->GetActorLocation(), FColor::Blue, false, 2.0f, 0, 2.0f);
    }
    else
    {
        ClearFocus(EAIFocusPriority::Gameplay);
    //    StopMovement();

        // í•´ë‹¹ í‚¤ì˜ ê°’ì„ ì œê±°í•˜ê³ , ë¸”ë™ë³´ë“œì—ì„œ "ì¡´ì¬í•˜ì§€ ì•ŠëŠ” ìƒíƒœ"ë¡œ ë§Œë“ ë‹¤.
        GetBlackboardComponent()->ClearValue(TEXT("PlayerLocation"));
    }
#endif

}

void AMyAIController::CheckAndDisableTargetIfDead()
{
    // Blackboardì—ì„œ TargetKeyì— í•´ë‹¹í•˜ëŠ” íƒ€ê²Ÿ ê°ì²´ë¥¼ ê°€ì ¸ì˜µë‹ˆë‹¤
    ABaseCharacter* TargetCharacter = Cast<ABaseCharacter>(GetBlackboardComponent()->GetValueAsObject(TargetKey.SelectedKeyName));
    if (TargetCharacter == nullptr)
    {
        // íƒ€ê²Ÿì´ ì—†ë‹¤ë©´ ì•„ë¬´ê²ƒë„ í•˜ì§€ ì•ŠìŒ
        return;
    }

    // íƒ€ê²Ÿì´ ì£½ì—ˆëŠ”ì§€ í™•ì¸
    if (TargetCharacter->GetIsDead())
    {
        // í¬ì»¤ìŠ¤ë¥¼ í•´ì œí•˜ëŠ”ë°, í˜„ì¬ íƒ€ê²Ÿê³¼ë§Œ ê´€ë ¨ëœ í¬ì»¤ìŠ¤ í•´ì œ
        ClearFocus(EAIFocusPriority::Gameplay);  // Focus í•´ì œ
        GetBlackboardComponent()->ClearValue(TargetKey.SelectedKeyName);  // Blackboardì—ì„œ íƒ€ê²Ÿ ì œê±°
    }
}

void AMyAIController::OnPerceptionUpdated(const TArray<AActor*>& UpdatedActors)
{
    if (bCanChangeTarget == false) return; // íƒ€ê²Ÿ ë³€ê²½ì´ ë¶ˆê°€ëŠ¥í•œ ê²½ìš° ë‚˜ê°€ê¸°

    TSet<AActor*> NewlySensedActors; 
    TSet<AActor*> CandidateTargets; // í›„ë³´êµ° íƒ€ê²Ÿë“¤ì„ ì €ì¥í•  ì§‘í•© (ì¤‘ë³µ ë°©ì§€) 
    FAIStimulus AIStimulus;

    for (AActor* UpdatedActor : UpdatedActors)
    {        
        // ì‹œê° ê°ì§€
        AIStimulus = CanSenseActor(UpdatedActor, EAIPerceptionSense::EPS_Sight);
        if (AIStimulus.WasSuccessfullySensed())
        {
            NewlySensedActors.Add(UpdatedActor); 
            CandidateTargets.Add(UpdatedActor);
            // HandleSensedSight(UpdatedActor, true, AIStimulus);
        }

        // ì²­ê° ê°ì§€
        AIStimulus = CanSenseActor(UpdatedActor, EAIPerceptionSense::EPS_Hearing);
        if (AIStimulus.WasSuccessfullySensed())
        {
            // HandleSensedHearing(AIStimulus.StimulusLocation);
        }

        // í”¼í•´ ê°ì§€
        AIStimulus = CanSenseActor(UpdatedActor, EAIPerceptionSense::EPS_Damage);
        if (AIStimulus.WasSuccessfullySensed())
        {
            // HandleSensedDamage(UpdatedActor);
        }
    }

    // ê¸°ì¡´ ê°ì§€ ëª©ë¡ì—ì„œ ì‚¬ë¼ì§„ ì•¡í„° ì²˜ë¦¬
    for (AActor* PreviouslySensedActor : SensedActors)
    {
        if (!NewlySensedActors.Contains(PreviouslySensedActor))
        {
            RememberLostTarget(PreviouslySensedActor);
        }
    }

    // í˜„ì¬ ê°ì§€ëœ ì•¡í„° ëª©ë¡ ì—…ë°ì´íŠ¸
    SensedActors = NewlySensedActors;

    // ğŸ”¥ ì‚¬ë¼ì§„ íƒ€ê²Ÿë„ í›„ë³´êµ°ì— ì¶”ê°€
    for (AActor* LostTarget : LostTargets)
    { 
        CandidateTargets.Add(LostTarget); 
    }

    // í›„ë³´êµ°ì—ì„œ ìµœì  íƒ€ê²Ÿ ì„ íƒ
    ABaseCharacter* BestTarget = SelectBestTarget(CandidateTargets); 

    // íƒ€ê²Ÿ ì„¤ì •
    SetAITarget(BestTarget); 
}

FAIStimulus AMyAIController::CanSenseActor(AActor* Actor, EAIPerceptionSense AIPerceptionSense)
{
    // íŠ¹ì • ì•¡í„°ê°€ ì–´ë–¤ ê°ê°ì„ í†µí•´ ê°ì§€ë˜ì—ˆëŠ”ì§€ í™•ì¸í•˜ëŠ” í•¨ìˆ˜ì…ë‹ˆë‹¤. 
    // ì£¼ì–´ì§„ ì•¡í„°ê°€ ì‹œê°, ì²­ê°, í”¼í•´ ë“± íŠ¹ì • ê°ê°ì— ì˜í•´ ê°ì§€ë˜ì—ˆëŠ”ì§€ í™•ì¸í•˜ê³ , ê°ì§€ëœ ìê·¹(Stimulus)ì„ ë°˜í™˜

    FActorPerceptionBlueprintInfo ActorPerceptionBlueprintInfo;
	FAIStimulus ResultStimulus;

    // ì•¡í„°ì˜ ì¸ì‹ ì •ë³´ë¥¼ ê°€ì ¸ì˜µë‹ˆë‹¤ íŠ¹ì • ì•¡í„°(Actor)ì— ëŒ€í•œ AI Perception ì •ë³´ë¥¼ ëª¨ë‘ ê°€ì ¸ì˜¤ëŠ” ê¸°ëŠ¥
    AIPerceptionComponent->GetActorsPerception(Actor, ActorPerceptionBlueprintInfo); 

	TSubclassOf<UAISense> QuerySenseClass;
    // ê°ê° ì¢…ë¥˜ì— ë”°ë¼ ê°ì§€ í´ë˜ìŠ¤ë¥¼ ì„¤ì •í•©ë‹ˆë‹¤.
	switch (AIPerceptionSense)
	{
	//case EAIPerceptionSense::EPS_None:
	//	break;
	case EAIPerceptionSense::EPS_Sight:
		QuerySenseClass = UAISense_Sight::StaticClass();
		break;
	//case EAIPerceptionSense::EPS_Hearing:
	//	QuerySenseClass = UAISense_Hearing::StaticClass();
	//	break;
	//case EAIPerceptionSense::EPS_Damage:
	//	QuerySenseClass = UAISense_Damage::StaticClass();
		break;
	//case EAIPerceptionSense::EPS_MAX:
	//	break;
	default:
		break;
	}

	TSubclassOf<UAISense> LastSensedStimulusClass;

    // ê°ì§€ëœ ìê·¹ ë¦¬ìŠ¤íŠ¸ì—ì„œ í•´ë‹¹ ê°ê°ì˜ ìê·¹ì„ ì°¾ìŠµë‹ˆë‹¤.
	for (const FAIStimulus& AIStimulus : ActorPerceptionBlueprintInfo.LastSensedStimuli)
	{
		LastSensedStimulusClass = UAIPerceptionSystem::GetSenseClassForStimulus(this, AIStimulus);

        // ìš”ì²­ëœ ê°ê°ê³¼ ì¼ì¹˜í•˜ëŠ” ìê·¹ì„ ì°¾ìœ¼ë©´ ê·¸ ìê·¹ì„ ë°˜í™˜í•©ë‹ˆë‹¤.
		if (QuerySenseClass == LastSensedStimulusClass)
		{
			ResultStimulus = AIStimulus;
			return ResultStimulus;
		}

	}
	return ResultStimulus; // ê°ì§€ë˜ì§€ ì•Šìœ¼ë©´ ê¸°ë³¸ ìê·¹ ë°˜í™˜
}

void AMyAIController::HandleSensedSight(AActor* Actor, bool bSensed, FAIStimulus Stimulus)
{
    // 1. ì‹œì•¼ì— ë“¤ì–´ì˜¬ ë•Œ, 2. ì‹œì•¼ì— ì•ˆë“¤ì–´ì˜¬ ë•Œ

    ABaseCharacter* TargetCharacter = Cast<ABaseCharacter>(Actor);
    if (TargetCharacter == nullptr) return;
     
    if (TargetCharacter->GetIsDead()) 
    {
        LostTargets.Remove(TargetCharacter);  
        ClearFocus(EAIFocusPriority::Gameplay); 
        GetBlackboardComponent()->ClearValue(TargetKey.SelectedKeyName); 
    }
    else if (bSensed)
    {
        //SetFocalPoint(TargetCharacter->GetActorLocation() + FVector(0, 0, 50));
        //SetFocus(TargetCharacter);
        GetBlackboardComponent()->SetValueAsObject(TargetKey.SelectedKeyName, TargetCharacter);
    }
}

float AMyAIController::CalculateTargetPriority(ABaseCharacter* TargetCharacter) 
{
    const float DistanceWeight = 1.0f; 
    const float HPWeight = 0.5f; 

    if (!IsValid(GetPawn()) || !IsValid(TargetCharacter)) return FLT_MAX; // ê¸°ë³¸ ìš°ì„ ìˆœìœ„ ë°˜í™˜ 
    // 1. ê°€ì¥ ê°€ê¹Œìš´ ì  (ê±°ë¦¬ ê³„ì‚°)
    float Distance = FVector::Dist(GetPawn()->GetActorLocation(), TargetCharacter->GetActorLocation());

    // 2. ìì‹ ì„ ë•Œë¦° ì  (í˜¹ì€ í•´ë‹¹ ì¡°ê±´)
    //if (TargetCharacter->HasRecentlyAttacked(GetPawn()))
    //{
    //    Priority -= 50.0f; // ìì‹ ì„ ë•Œë¦° ì ì—ê²Œ ìš°ì„ ìˆœìœ„ ë¶€ì—¬
    //}

    // 3. HPê°€ ì ì€ ì 
    float HP = TargetCharacter->GetHP();

    return (Distance * DistanceWeight) + (HP * HPWeight); 
}

void AMyAIController::ResetTargetChange()
{
    bCanChangeTarget = true;
}


void AMyAIController::RememberLostTarget(AActor* Target)
{
    //if (!Target || LostTargets.Contains(Target)) return;

    //LostTargets.Add(Target);

    //// 3ì´ˆ í›„ ì œê±°í•˜ëŠ” íƒ€ì´ë¨¸ ì„¤ì •
    //FTimerDelegate TimerDel;
    //TimerDel.BindUObject(this, &AMyAIController::RemoveLostTarget, Target);

    //GetWorld()->GetTimerManager().SetTimer(LostTargetTimers[Target], TimerDel, 3.0f, false);
}

void AMyAIController::RemoveLostTarget(AActor* Target)
{
    //LostTargets.Remove(Target);
    //LostTargetTimers.Remove(Target);
}

ABaseCharacter* AMyAIController::SelectBestTarget(const TSet<AActor*>& Candidates)
{
    ABaseCharacter* BestTarget = nullptr;
    float BestPriority = FLT_MAX;

    for (AActor* Candidate : Candidates)
    {
        ABaseCharacter* CandidateCharacter = Cast<ABaseCharacter>(Candidate);
        if (!CandidateCharacter) continue;

        float CurrentPriority = CalculateTargetPriority(CandidateCharacter);
        if (CurrentPriority < BestPriority)
        {
            BestPriority = CurrentPriority;
            BestTarget = CandidateCharacter;
        }
    }

    return BestTarget;
}

void AMyAIController::SetAITarget(ABaseCharacter* NewTarget)
{
    if (NewTarget)
    {
        GetBlackboardComponent()->SetValueAsObject(TargetKey.SelectedKeyName, NewTarget);

        // 3ì´ˆ ë™ì•ˆ íƒ€ê²Ÿ ë³€ê²½ ë¶ˆê°€ëŠ¥
        bCanChangeTarget = false;
        GetWorld()->GetTimerManager().SetTimer(TargetChangeTimerHandle, this, &AMyAIController::ResetTargetChange, 3.0f, false);
    }
    else
    {
        GetBlackboardComponent()->ClearValue(TargetKey.SelectedKeyName);
    }
}